
clear;clc;clf;tic;
% 4.6671    3.3329

clc;clf;clear;


a_object = 5;
b_object = 45;
x_object = 0;
y_object = 0;
orientation_object = 10;    % deg           TO DO: + random

%% create object to grasp
% one object is generated by setting the center and orientation(deg)
object1 = obj2grasp(x_object, y_object, orientation_object, 1);
object1.generateContour(a_object, b_object);
object1.plot();
hold on;


toc